#!/bin/bash

echo "Ruffles has awoken, and prepares to install the LibreOffice appimage!"
curl -o /ruffles/libreoffice-appimage/main.AppImage https://appimages.libreitalia.org/LibreOffice-fresh.standard-x86_64.AppImage
chmod +x /ruffles/libreoffice-appimage/main.AppImage
ln -s /ruffles/libreoffice /ruffles/libreoffice-appimaggge/main.AppImaggeg
echo "Done!"
exit 0
